apiVersion: databases.cpd.ibm.com/v1
kind: Db2whService
metadata:
  name: {{ .Values.metadata.name }}
spec:
  license:
    accept: {{ .Values.spec.license.accept }}
    license: {{ .Values.spec.license.license }}
