apiVersion: ds.cpd.ibm.com/v1
kind: DataStage
metadata:
  name: {{ .Values.metadata.name }}
spec:
  license:
    accept: {{ .Values.spec.license.accept }}
    license:  {{ .Values.spec.license.license }}
  version: {{ .Values.spec.version }}
  fileStorageClass: {{ .Values.spec.fileStorageClass }}
  blockStorageClass: {{ .Values.spec.blockStorageClass }}