apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: {{ .Values.metadata.name }}
spec:
  license:
    accept: {{ .Values.spec.license.accept }}
    license: {{ .Values.spec.license.license }}
  fileStorageClass: {{ .Values.spec.fileStorageClass }}
  blockStorageClass: {{ .Values.spec.blockStorageClass }}
  version: {{ .Values.spec.version }}